### PR TITLE
Gemfile dependency for rack

### PR DESCRIPTION
**Pull request by mikebaldry**
This is too specific and it was causing me problems when using other gems. I've changed the version of rack required to be ~> 1.2 which works fine for me now.

### CODE REVIEW

**Comment by toolmantim** [comment]
+1

**Comment by juliocesar** [comment]
Thanks. Yeah, I'll remove the version requirement of Rack completely, as matter of fact.

Not sure about the dalli commits included on this one. I'll take them as suggestions though. I had initially considered it for memcached, but at the time it just didn't work for me.

**Comment by mikebaldry** [comment]
Hey that was my first pull request, I didn't realise commits after the pull request would appear too.

Though it works fine for me I left it separate from the memcache store anyway. I needed it to get pagespeed working on heroku as they don't allow disk writing and their memcache server has SASL so requires dalli as other gems don't support that.

Can I suggest making the store/filter loader work differently in that you can just add a class to the right namespace in my own project? If you do this it tries to require the file in the folder of your gem lib/store which causes an exception. I cb put a pull request for that if you like?

Also, why is there no css minification? I was thinking of implementing it.

Thanks

Sent from my HTC

----- Reply message -----
From: "juliocesar" reply@reply.github.com
To: "Michael Baldry" Michael.Baldry@uswitch.com
Subject: [rack-pagespeed] Gemfile dependency for rack (#27)
Date: Fri, May 20, 2011 01:31

Thanks. Yeah, I'll remove the version requirement of Rack completely, as matter of fact.

Not sure about the dalli commits included on this one. I'll take them as suggestions though. I had initially considered it for memcached, but at the time it just didn't work for me.

## 

Reply to this email directly or view it on GitHub:
https://github.com/juliocesar/rack-pagespeed/pull/27#issuecomment-1207342

*
*
uSwitch is here to take the confusion out of finding the best
deal, we do your searching and switching and you save money,
try us at www.uswitch.com

This email is intended only for the use of the individual or
entity to which it is addressed and may contain information that
is confidential, subject to copyright or which constitutes a
trade secret. You should not copy it for any purpose or disclose
its contents to any person. uSwitch Ltd has taken reasonable
precautions to minimise the risk of transmitting software
viruses but we advise you to carry out your own virus checks on
any attachment to this message. We cannot accept any liability
for any loss or damage resulting from any software viruses. If 
you receive this email in error, please email 
postmaster@uswitch.com and delete all copies on your system.

uSwitch Ltd, Floor 2, Centro 3, 19 Mandela Street, London, NW1 0DU
Company No. 03612689

**Comment by swrobel** [comment]
Gemfile.lock still specifies Rack 1.2.1 so even bundling the gem from github fails when using latest thin gem which wants Rack 1.2.2

**Pull request closed without merging**
